import { Palette, Button } from "std-widgets.slint";
import { NavBar } from "nav-bar.slint";
import { XiaoxinPageData } from "xiaoxin-page-data.slint";
import { EvaluationPageData } from "evaluation-page-data.slint";
import { FaceSigninPageData } from "facesignin-page-data.slint";
import { DeskcleanPageData } from "deskclean-page-data.slint";
import { XiaoxinPage } from "xiaoxin-page.slint";
import { EvaluationPage } from "evaluation-page.slint";
import { FaceSigninPage } from "facesignin-page.slint";
import { DeskcleanPage } from "deskclean-page.slint";
import { Sizing } from "sizing.slint";
export { XiaoxinPageData, EvaluationPageData, FaceSigninPageData, DeskcleanPageData }

export global AppData {
    in-out property<int> current-tab: 0;
    callback stop-app();
    callback tab-changed(int);
    callback swap-cameras();
}

export component AppWindow inherits Window {
    title: "电拖装接评估";
    preferred-height: 100%;
    preferred-width: 100%;
    height: Sizing.screen-height;
    width: Sizing.screen-width;
    default-font-size: root.width < 801px ? 14px : 32px;
    init => {
        // 强制设置深色模式
        Palette.color-scheme = ColorScheme.dark;
    }

    callback show-temporary-message(string);

    private property<string> temporary-message-text: "";
    private property<int> last-tab: -1;

    VerticalLayout {
        padding: 0px;
        spacing: 0px;

        Rectangle {
            min-height: root.height - 55px;
            clip: true;

            if AppData.current-tab == 0 : XiaoxinPage { root-screen-width: root.width; }
            if AppData.current-tab == 1 : EvaluationPage { root-screen-width: root.width; }
            if AppData.current-tab == 2 : FaceSigninPage { root-screen-width: root.width; }
            if AppData.current-tab == 3 : DeskcleanPage { root-screen-width: root.width; }
        }

        NavBar {
            height: 55px;
            current-index <=> AppData.current-tab;
            tabs: ["小新智能体", "工艺打分", "人脸签到", "工位清洁"];
            tab-changed(index) => {
                AppData.tab-changed(index);
            }
        }
    }

    HorizontalLayout {
        x: root.width - self.width;
        y: 0px;
        width: max(root.width * 25%, 120px);
        height: 50px;
        Button {
            text: "⇄";
            y: 0px;
            clicked => { AppData.swap-cameras(); show-temporary-message("正在切换摄像头") }
        }
        Button {
            text: (Palette.color-scheme == ColorScheme.light) ? "🌣" : "☽";
            y: 0px;
            clicked => {
                Palette.color-scheme = (Palette.color-scheme == ColorScheme.light) ? ColorScheme.dark : ColorScheme.light;
            }
        }
        Button {
            text: " X ";
            y: 0px;
            clicked => { AppData.stop-app(); }
        }
    }

    tab-watcher := Timer {
        interval: 120ms;
        running: true;
        triggered => {
            if (AppData.current-tab != root.last-tab) {
                AppData.tab-changed(AppData.current-tab);
                root.last-tab = AppData.current-tab;
            }
        }
    }

    message-popup := PopupWindow {
        close-policy: close-on-click;
        width: Sizing.screen-width;
        height: Sizing.large;

        Rectangle {
            background: #fafafa;
            border-color: #606060;
            border-width: 1px;
            Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: root.temporary-message-text;
                font-size: Sizing.large;
                color: black;
            }
        }
    }

    show-temporary-message(msg) => {
        root.temporary-message-text = msg;
        message-popup.show();
    }
}
