import {
    Palette,
    GroupBox,
    ProgressIndicator,
    HorizontalBox,
    VerticalBox,
    Button
} from "std-widgets.slint";
import { DeskcleanPageData } from "deskclean-page-data.slint";

export component DeskcleanStatusWidget {
    in property <length> root-screen-width;

    GroupBox {
        title: "工位清洁状态";
        height: 100%;
        width: 100%;
        VerticalLayout {
            alignment: start;
            spacing: 18px;
            Text {
                text: "1. 工具就位：";
                font-weight: 800;
            }
            HorizontalLayout {
                spacing: 10px;
                alignment: center;

                VerticalLayout {
                    alignment: center;
                    spacing: 4px;
                    Rectangle {
                        width: 64px;
                        height: 64px;
                        border-radius: 8px;
                        background: DeskcleanPageData.screwdriver-ready ? #4CAF50 : #ff3b25;
                        Image {
                            height: 80%;
                            width: 80%;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                            source: @image-url("icon/tools_phillips.svg");
                            colorize: Palette.foreground;
                        }
                    }

                    Text {
                        text: "螺丝刀";
                    }
                }

                VerticalLayout {
                    alignment: center;
                    spacing: 4px;
                    Rectangle {
                        width: 64px;
                        height: 64px;
                        border-radius: 8px;
                        background: DeskcleanPageData.wire-stripper-ready ? #4CAF50 : #ff3b25;
                        Image {
                            height: 80%;
                            width: 80%;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                            source: @image-url("icon/tools_pliers_wire_stripper.svg");
                            colorize: Palette.foreground;
                        }
                    }

                    Text {
                        text: "剥线钳";
                    }
                }

                VerticalLayout {
                    alignment: center;
                    spacing: 4px;
                    Rectangle {
                        width: 64px;
                        height: 64px;
                        border-radius: 8px;
                        background: DeskcleanPageData.multimeter-ready ? #4CAF50 : #ff3b25;
                        Image {
                            height: 80%;
                            width: 80%;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                            source: @image-url("icon/margin.svg");
                            colorize: Palette.foreground;
                        }
                    }

                    Text {
                        text: "万用表";
                    }
                }

                VerticalLayout {
                    alignment: center;
                    spacing: 4px;
                    Rectangle {
                        width: 64px;
                        height: 64px;
                        border-radius: 8px;
                        background: DeskcleanPageData.crimping-ready ? #4CAF50 : #ff3b25;
                        Image {
                            height: 80%;
                            width: 80%;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                            source: @image-url("icon/plumbing.svg");
                            colorize: Palette.foreground;
                        }
                    }

                    Text {
                        text: "压线钳";
                    }
                }
            }

            VerticalLayout {
                spacing: 16px;
                Text {
                    text: "2. 桌面无杂物：";
                    font-weight: 800;
                }

                ProgressIndicator {
                    height: 24px;
                    progress: DeskcleanPageData.clean-progress;
                    animate progress { duration: 300ms; }
                }

                Text {
                    text: "桌面：" + Math.round(DeskcleanPageData.clean-progress * 100) + " 分";
                    font-size: root.root-screen-width < 801px ? 48px : 52px;
                    font-weight: 1600;
                    horizontal-alignment: center;
                }
            }
        }
    }
    Button {
        x: parent.width - self.width - 4px;
        y: 36px;
        text: "提交";
        clicked => DeskcleanPageData.deskclean-submit();
    }
}
