import {
    Palette,
    GroupBox,
    ProgressIndicator,
    HorizontalBox,
    VerticalBox,
    Button,
    StyleMetrics,
} from "std-widgets.slint";
import { DeskcleanPageData } from "deskclean-page-data.slint";

component ToolStatusBox {
    in property <string> name;
    in property <image> icon;
    in property <bool> is-ready;
    VerticalLayout {
        alignment: center;
        spacing: StyleMetrics.layout-spacing;
        Rectangle {
            height: self.width;
            border-radius: 8px;
            background: is-ready ? #4CAF50 : #ff3b25;
            Image {
                height: 80%;
                width: 80%;
                vertical-alignment: center;
                horizontal-alignment: center;
                source: icon;
                colorize: Palette.foreground;
            }
        }
        Text {
            text: name;
        }
    }
}

export component DeskcleanStatusWidget {
    in property <length> root-screen-width;

    GroupBox {
        title: " ";
        height: 100%;
        width: 100%;
        VerticalLayout {
            alignment: start;
            spacing: StyleMetrics.layout-spacing;
            Text {
                text: "1. 工具就位：";
                font-weight: 800;
            }
            HorizontalLayout {
                spacing: StyleMetrics.layout-spacing;
                alignment: center;

                ToolStatusBox {
                    name: "螺丝刀";
                    icon: @image-url("icon/tools_phillips.svg");
                    is-ready: DeskcleanPageData.screwdriver-ready;
                }
                ToolStatusBox {
                    name: "剥线钳";
                    icon: @image-url("icon/tools_pliers_wire_stripper.svg");
                    is-ready: DeskcleanPageData.wire-stripper-ready;
                }
                ToolStatusBox {
                    name: "万用表";
                    icon: @image-url("icon/margin.svg");
                    is-ready: DeskcleanPageData.multimeter-ready;
                }
                ToolStatusBox {
                    name: "压线钳";
                    icon: @image-url("icon/plumbing.svg");
                    is-ready: DeskcleanPageData.crimping-ready;
                }
            }

            Rectangle {
                height: StyleMetrics.layout-spacing;
            }

            VerticalLayout {
                spacing: StyleMetrics.layout-spacing;
                Text {
                    text: "2. 桌面无杂物：";
                    font-weight: 800;
                }

                ProgressIndicator {
                    height: 24px;
                    progress: DeskcleanPageData.clean-progress;
                    animate progress { duration: 300ms; }
                }

                Text {
                    text: "桌面：" + Math.round(DeskcleanPageData.clean-progress * 100) + " 分";
                    font-size: root.root-screen-width < 801px ? 48px : 52px;
                    font-weight: 1600;
                    horizontal-alignment: center;
                }
            }
        }
    }
    Button {
        x: parent.width - self.width - 4px;
        y: parent.height - self.height - 4px;
        text: "提交";
        clicked => DeskcleanPageData.deskclean-submit();
    }
}
