import { FaceSigninPageData } from "facesignin-page-data.slint";
import { CameraViewport } from "camera-viewport.slint";
import { SigninStatusWidget } from "facesignin-status.slint";

export component FaceSigninPage {
    in property <length> root-screen-width;

    height: 100%;
    width: 100%;

    private property <bool> is-portrait: root.height > root.width;

    VerticalLayout {
        width: is-portrait ? root.width : (root.root-screen-width < 801px ? root.width / 2.1 : root.width / 1.7);
        height: is-portrait ? root.height * 0.4 : root.height;
        x: 0;
        y: 0;

        CameraViewport {
            width: 100%;
            height: 100%;
            frame <=> FaceSigninPageData.camera-frame;
            running <=> FaceSigninPageData.signin-running;
            request-camera-frame => { FaceSigninPageData.request-signin-frame(); }
        }
    }

    VerticalLayout {
        padding: 10px;
        height: is-portrait ? root.height * 0.6 : root.height;
        width: is-portrait ? root.width : (root.root-screen-width < 801px ? root.width / 1.9 : root.width / 2.45);
        x: is-portrait ? 0 : root.width - self.width;
        y: is-portrait ? root.height * 0.4 : 0;

        SigninStatusWidget {}
    }
}
