import { VerticalBox } from "std-widgets.slint";

export component FaceSigninViewport {
    in-out property<image> frame;
    in property<bool> running: true;
    callback request-signin-frame();

    timer := Timer {
        interval: 16ms;
        running: root.running;
        triggered => { root.request-signin-frame(); }
    }

    Image {
        width: 100%;
        height: 100%;
        source: root.frame;
        image-fit: contain;
    }
}
