import { HorizontalBox, VerticalBox, GroupBox } from "std-widgets.slint";
import { FaceSigninViewport } from "face-signin-viewport.slint";
import { SigninStatusWidget } from "signin-status.slint";

export component FaceSigninPage {
    in-out property<image> signin-frame;
    in-out property<image> signin-aligned-frame;
    in-out property<string> signin-status-text: "";
    in-out property<int> signin-progress-percent: 0;
    in-out property<bool> signin-running: true;

    callback request-signin-frame();

    HorizontalBox {
        width: 1100px;
        height: 600px;

        GroupBox {
            VerticalBox {
                FaceSigninViewport {
                    frame <=> root.signin-frame;
                    running <=> root.signin-running;
                    request-signin-frame => { root.request-signin-frame(); }
                }
            }
        }

        VerticalBox {
            width: 450px;
            SigninStatusWidget {
                status-text: root.signin-status-text;
                progress-percent: root.signin-progress-percent;
                aligned-frame: root.signin-aligned-frame;
            }
        }
    }
}
