import { Palette, GroupBox, Spinner, HorizontalBox } from "std-widgets.slint";
import { FaceSigninPageData } from "facesignin-page-data.slint";

export component SigninStatusWidget {
    GroupBox {
        title: "签到状态";
        height: 100%;
        width: 100%;
        Rectangle {
            HorizontalLayout {
                y: 0;
                alignment: center;
                Rectangle {
                    min-width: 200px;
                    preferred-width: 350px;
                    height: self.width;
                    Rectangle {
                        width: 100%;
                        height: 100%;
                        background: Palette.alternate-background;
                    }
                    Image {
                        width: 100%;
                        height: 100%;
                        source: FaceSigninPageData.signin-aligned-frame;
                        image-fit: contain;
                    }
                }
            }
            VerticalLayout {
                y: root.height - self.height - 90px;
                height: 120px;
                spacing: 8px;
                Text {
                    horizontal-alignment: center;
                    font-size: 36px;
                    text: FaceSigninPageData.signin-status-text;
                }
                Spinner {
                    height: 48px;
                    progress: FaceSigninPageData.signin-progress-percent / 100.0;
                    indeterminate: FaceSigninPageData.signin-progress-percent == 0;
                }
            }
        }
    }
}
