import { Palette, GroupBox, Spinner, HorizontalBox, StyleMetrics } from "std-widgets.slint";
import { FaceSigninPageData } from "facesignin-page-data.slint";

export component SigninStatusWidget {
    GroupBox {
        title: " ";
        height: 100%;
        width: 100%;
        Rectangle {
            HorizontalLayout {
                y: 0;
                alignment: center;
                Rectangle {
                    min-width: 200px;
                    preferred-width: 350px;
                    height: self.width;
                    Rectangle {
                        width: 100%;
                        height: 100%;
                        background: Palette.background;
                    }
                    Image {
                        width: 100%;
                        height: 100%;
                        source: FaceSigninPageData.signin-aligned-frame;
                        image-fit: contain;
                    }
                }
            }
            VerticalLayout {
                height: 200px;
                spacing: StyleMetrics.layout-spacing;
                y: parent.height - self.height;
                padding-bottom: 55px;
                Text {
                    horizontal-alignment: center;
                    font-size: root.height * 10%;
                    text: FaceSigninPageData.signin-status-text;
                }
                Spinner {
                    height: root.height * 10%;
                    progress: FaceSigninPageData.signin-progress-percent / 100.0;
                    indeterminate: FaceSigninPageData.signin-progress-percent == 0;
                }
            }
        }
    }
}
