import { Button, LineEdit, VerticalBox, GroupBox } from "std-widgets.slint";

export component SettingsWidget {
    in-out property <string> server-ip;
    callback save-settings(string);

    GroupBox {
        title: "设置";
        VerticalBox {
            spacing: 8px;
            alignment: start;

            Text {
                text: "SERVER IP:";
            }

            LineEdit {
                min-width: 200px;
                text <=> root.server-ip;
                placeholder-text: "192.168.100.XXX";
            }

            Button {
                text: "保存";
                clicked => {
                    root.save-settings(root.server-ip);
                }
            }
        }
    }
}
