import { Button, VerticalBox, HorizontalBox, GroupBox, CheckBox, ListView } from "std-widgets.slint";

export component ShotsStatusWidget {
    in property <string> current-detection-text;
    in property <string> totals-text;

    in-out property <int> current-shot-position: 1;
    in-out property <bool> inference-enabled: false;
    in-out property <bool> udp-enabled: false;
    in property <[string]> shots;

    callback set-shot-position(int);
    callback toggle-inference(bool);
    callback toggle-udp(bool);
    callback capture-dataset();
    callback capture-shot();
    callback clear-shots();
    callback confirm-shots();

    GroupBox {
        title: "拍照状态";
        width: 100%;
        VerticalLayout {
            alignment: LayoutAlignment.start;
            spacing: 8px;
            visible: true;
            Text {
                text: root.current-detection-text;
                font-size: 16px;
                font-weight: 800;
            }
            Text {
                text: root.totals-text;
                font-size: 16px;
                font-weight: 1600;
            }

            HorizontalLayout {
                spacing: 6px;
                VerticalLayout {
                    alignment: center;
                    Text { text: "当前:"; }
                }

                Button {
                    text: "第一张";
                    enabled: root.current-shot-position != 1;
                    clicked => { root.set-shot-position(1); }
                }
                Button {
                    text: "第二张";
                    enabled: root.current-shot-position != 2;
                    clicked => { root.set-shot-position(2); }
                }
                Button {
                    text: "第三张";
                    enabled: root.current-shot-position != 3;
                    clicked => { root.set-shot-position(3); }
                }
            }

            CheckBox {
                text: "端侧 AI 视觉推理";
                checked <=> root.inference-enabled;
                toggled => { root.toggle-inference(self.checked); }
            }

            CheckBox {
                text: "UDP 图传";
                checked <=> root.udp-enabled;
                toggled => { root.toggle-udp(self.checked); }
            }

            HorizontalBox {
                spacing: 8px;
                Button {
                    text: "拍照";
                    clicked => { root.capture-shot(); }
                }
                Button {
                    text: "图像采集";
                    clicked => { root.capture-dataset(); }
                }
                Button {
                    text: "清除";
                    clicked => { root.clear-shots(); }
                }
                Button {
                    text: "确认";
                    clicked => { root.confirm-shots(); }
                }
            }

            Rectangle {
                height: 90px;
                border-color: #505050;
                border-width: 1px;
                clip: true;

                ListView {
                    height: 100%;
                    width: 100%;
                    for s in root.shots : Text {
                        text: s;
                    }
                }
            }
        }
    }
}
