import { Button, GroupBox, HorizontalBox, ListView, Switch, Palette } from "std-widgets.slint";
import { EvaluationPageData } from "evaluation-page-data.slint";

export component ShotsStatusWidget {
    in property <length> root-screen-width;

    GroupBox {
        title: "拍照状态";
        height: 100%;
        width: 100%;
        VerticalLayout {
            spacing: 6px;
            Text {
                text: "工艺 " + EvaluationPageData.score + " 分";
                font-size: root.root-screen-width < 801px ? 48px : 52px;
                font-weight: 1600;
                horizontal-alignment: center;
            }

            Rectangle {
                height: 50px;
                Text {
                    y: 0;
                    text: EvaluationPageData.detection-description;
                    font-size: root.root-screen-width < 801px ? 16px : 28px;
                    color: Palette.control-foreground;
                    font-weight: 400;
                    horizontal-alignment: left;
                    wrap: word-wrap;
                }
            }
            Rectangle {
            }

            VerticalLayout {
                height: 120px;
                HorizontalLayout {
                    Switch {
                        text: "UDP 图传";
                        checked <=> EvaluationPageData.udp-enabled;
                        toggled => { EvaluationPageData.toggle-udp(self.checked); }
                    }
                    Switch {
                        text: "切图推理";
                        checked <=> EvaluationPageData.tile-inference-enabled;
                        toggled => { EvaluationPageData.toggle-tile-inference(self.checked); }
                    }
                }

                HorizontalLayout {
                    spacing: 6px;
                    Button {
                        text: "拍照";
                        clicked => { EvaluationPageData.capture-shot(); }
                    }
                    Button {
                        text: "采集";
                        clicked => { EvaluationPageData.capture-dataset(); }
                    }
                    Button {
                        text: "清除";
                        clicked => { EvaluationPageData.clear-shots(); }
                    }
                }
            }
        }
    }
}
