import { GroupBox, VerticalBox, ListView, Spinner, HorizontalBox } from "std-widgets.slint";

export component SigninStatusWidget {
    in property<string> status-text;
    in property<string> person-text;
    in property<[string]> logs;
    in property<image> aligned-frame;
    in property<int> progress-percent: 0;

    GroupBox {
        title: "签到状态";
        height: 100%;
        width: 100%;
        Rectangle {
            HorizontalLayout {
                y: 0;
                alignment: center;
                Rectangle {
                    min-width: 200px;
                    preferred-width: 350px;
                    height: self.width;
                    Rectangle {
                        width: 100%;
                        height: 100%;
                        background: black;
                    }
                    Image {
                        width: 100%;
                        height: 100%;
                        source: aligned-frame;
                        image-fit: contain;
                    }
                }
            }
            VerticalLayout {
                y: root.height - self.height - 90px;
                height: 120px;
                spacing: 8px;
                Text {
                    horizontal-alignment: center;
                    font-size: 36px;
                    text: status-text;
                }
                Spinner {
                    height: 48px;
                    progress: progress-percent / 100.0;
                    indeterminate: progress-percent == 0;
                }
            }
        }
    }
}
