import { GroupBox, VerticalBox, ListView } from "std-widgets.slint";

export component SigninStatusWidget {
    in property<string> status-text;
    in property<string> person-text;
    in property<[string]> logs;

    GroupBox {
        title: "签到状态";
        VerticalBox {
            spacing: 8px;
            Text { text: status-text; }
            Text { text: person-text; }

            Rectangle {
                height: 90px;
                border-color: #505050;
                border-width: 1px;
                clip: true;

                ListView {
                    height: 100%;
                    width: 100%;
                    for row in logs : Text { text: row; }
                }
            }
        }
    }
}
