export global XiaoxinPageData {
    in-out property<image> camera-frame;
    in-out property<bool> xiaoxin-running: false;

    // "idle" | "evaluate_need_troubleshoot"
    in-out property<string> status-type: "idle";

    // 故障类型，如 "M1_NOT_START"
    in-out property<string> evaluate_need_troubleshoot_type: "";

    // 故障主动发现弹窗
    in-out property<bool> show-troubleshoot-popup: false;
    in-out property<string> troubleshoot-title: "电动机M1不工作？";
    in-out property<bool> show-troubleshoot-solution-popup: false;
    in-out property<string> troubleshoot-solution-desc: "1. 检查电机 M1 的电源线是否正确连接\n2.检查变频器输出端 U/V/W 是否接对";

    // 教育资源 widget（点击头像展开）
    in-out property<bool> show-edu-widget: false;

    callback request-xiaoxin-frame();
    callback help-me-solve();
}
