import { RadarAxis } from "radar-chart.slint";

export global XiaoxinPageData {
    in-out property<image> camera-frame;
    in-out property<bool> xiaoxin-running: false;

    in-out property<string> status-text: "";
    in-out property<string> insights-text: "我在看着哦";

    in-out property<string> vl-response-text: "";
    in-out property<bool> vl-is-streaming: false;

    in-out property <[RadarAxis]> insight_7s_data: [
        { label: "整理", value: 0.60 },
        { label: "整顿", value: 0.20 },
        { label: "清扫", value: 0.60 },
        { label: "清洁", value: 0.60 },
        { label: "素养", value: 0.75 },
        { label: "安全", value: 0.90 },
        { label: "节约", value: 0.50 }
    ];
        
    // 故障主动发现弹窗
    in-out property<bool> show-troubleshoot-popup: false;
    in-out property<string> troubleshoot-title: "电动机M1不工作？";
    in-out property<bool> show-troubleshoot-solution-popup: false;
    in-out property<string> troubleshoot-solution-desc: "1. 检查电机 M1 的电源线是否正确连接\n2.检查变频器输出端 U/V/W 是否接对";

    // 教育资源 widget（点击头像展开）
    in-out property<bool> show-edu-widget: false;

    callback request-xiaoxin-frame();
}
